---
# NOTE: Terraform-managed template

changelog:
  exclude:
    authors:
      - tagdots-owner

  categories:
    - title: "🚀 New features"
      labels:
        - feature
    - title: "🎉 Change features"
      labels:
        - enhancement
    - title: "🐛 Fixes"
      labels:
        - fix
        - hotfix
        - bugfix
    - title: "🛠️ Maintenance"
      labels:
        - dependencies
    - title: "👒 Others"
      labels:
        - build
        - documentation
        - style
        - test
