---
commitizen:
  major_version_zero: false
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.0.0
  version_provider: commitizen
  version_scheme: pep440
