repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
  - name: Check GitHub Actions Workflows
    id: check-github-workflows
    args:
    - --verbose
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - name: Check YAML to verify syntax
    id: check-yaml
  - name: Check added large files
    id: check-added-large-files
    args:
    - --maxkb=2000
  - name: Fix newline at end of file
    id: end-of-file-fixer
    exclude: ^.gitignore$|^LICENSE$
  - name: Fix to trim whitespace from ends of lines
    id: trailing-whitespace
    exclude: ^.gitignore$
