name: update-pre-commit-action

description: 'Run update-pre-commit to keep pre-commit hooks up to date and optionally create pull request'

author: tagdots

branding:
  icon: activity
  color: green

inputs:
  dry-run:
    description: 'Dry Run'
    default: 'false'

  file:
    description: 'File to update'
    default: '.pre-commit-config.yaml'

  open-pr:
    description: 'Open Pull Request'
    default: 'true'

runs:
  using: "composite"

  steps:

  - name: Checkout source code
    uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

  - name: Install Python
    uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
    with:
      python-version: '3.14.x'

  - name: Install the latest update-pre-commit
    shell: bash
    run: python -m pip install update-pre-commit

  - name: Run update-pre-commit to show version
    shell: bash
    run: update-pre-commit --version

  - name: Run update-pre-commit
    shell: bash
    env:
      INPUT_DRY_RUN: ${{ inputs.dry-run }}
      INPUT_FILE: ${{ inputs.file }}
      INPUT_OPEN_PR: ${{ inputs.open-pr }}
    run: update-pre-commit --dry-run ${INPUT_DRY_RUN} --file ${INPUT_FILE} --open-pr ${INPUT_OPEN_PR}
