name: update-pre-commit-action

description: 'Run update-pre-commit to keep pre-commit hooks up to date and optionally create pull request'

author: tagdots

branding:
  icon: activity
  color: green

inputs:
  dry-run:
    description: 'Dry Run'
    default: 'false'

  file:
    description: 'File to update'
    default: '.pre-commit-config.yaml'

  open-pr:
    description: 'Open Pull Request'
    default: 'true'

runs:
  using: "composite"

  steps:

  - name: Checkout source code
    uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  - name: Install Python
    uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
    with:
      python-version: '3.12.x'

  - name: Install the latest update-pre-commit
    shell: bash
    run: python -m pip install update-pre-commit

  - name: Run update-pre-commit to show version
    shell: bash
    run: update-pre-commit --version

  - name: Run update-pre-commit
    shell: bash
    env:
      INPUT_DRY_RUN: ${{ inputs.dry-run }}
      INPUT_FILE: ${{ inputs.file }}
      INPUT_OPEN_PR: ${{ inputs.open-pr }}
    run: update-pre-commit --dry-run ${INPUT_DRY_RUN} --file ${INPUT_FILE} --open-pr ${INPUT_OPEN_PR}
