---
name: re-build-test

on: # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      ARTIFACT_ID:
        value: ${{ jobs.build.outputs.ARTIFACT_ID }}

      BUILD_VERSION:
        value: ${{ jobs.build.outputs.BUILD_VERSION }}

      WORKFLOW_RUN_ID:
        value: ${{ jobs.build.outputs.WORKFLOW_RUN_ID }}

  workflow_dispatch:

env:
  PACKAGE_NAME: update_pre_commit_acition
  PYTHON_VERSION: "3.14.x"
  TERRAFORM_VERSION: "1.15.x"
  UV_VERSION: "0.12.3"

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      ARTIFACT_ID: "000-111-222"
      WORKFLOW_RUN_ID: "000-111-333"
      BUILD_VERSION: ${{ steps.set-build-version.outputs.BUILD_VERSION }}

    steps:
      - name: Checkout source code # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python # https://github.com/marketplace/actions/setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: Set build version
        id: set-build-version
        shell: bash
        run: |
          echo "BUILD_VERSION=$(cz version -p)" >> "$GITHUB_OUTPUT"

      - name: Get build version
        id: get-build-version
        shell: bash
        run: |
          echo "Build Version: ${{ steps.set-build-version.outputs.BUILD_VERSION }}"
