---

name: sidecar-pr-target

on:  # yamllint disable-line rule:truthy
  pull_request_target:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ github.repository }}

    # https://github.com/marketplace/actions/labeler
    - id: label-pr
      uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d #v6.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "${{ steps.label-pr.outputs.all-labels }}"

  notify-slack:
    runs-on: ubuntu-latest

    steps:

    - name: Slack message on PR activities
      uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_PR }}"
          text: ":fire: *Pull Request (re)opened or updated.*
          ```
          Repo  : ${{ github.repository }}\n
          Branch: ${{ github.event.pull_request.head.ref }}\n
          PR URL: ${{ github.event.pull_request.html_url }}
          ```"
