---
name: sidecar-pr-target

on: # yamllint disable-line rule:truthy
  pull_request_target:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ github.repository }}

      - name: Label PR
        id: label-pr # https://github.com/marketplace/actions/labeler
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 #v7.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get labeled PR
        shell: bash
        run: echo "${{ steps.label-pr.outputs.all-labels }}"

  notify-slack:
    if: always()
    needs: labeler
    runs-on: ubuntu-latest

    steps:
      - name: Slack message on PR # https://github.com/slackapi/slack-github-action
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}
          payload: >
            {
              "channel": "${{ secrets.SECRET_SLACK_CHANNEL_PR }}",
              "text": ":fire: *Pull Request (re)opened or updated.*```
                \nRepo  : ${{ github.repository }}
                \nBranch: ${{ github.event.pull_request.head.ref }}
                \nPR URL: ${{ github.event.pull_request.html_url }}```"
            }
